# Generated by Django 3.2.7 on 2022-10-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221004_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=35, unique=True)),
                ('ver', models.BooleanField(default=False)),
                ('agregar', models.BooleanField(default=False)),
                ('actualizar', models.BooleanField(default=False)),
                ('borrar', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
    ]
