# Generated by Django 3.2.7 on 2022-10-04 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_permisos'),
    ]

    operations = [
        migrations.AddField(
            model_name='permisos',
            name='id_rol',
            field=models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.rol'),
        ),
    ]
