# Generated by Django 3.2.7 on 2022-10-28 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_usuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisos',
            name='nombre',
            field=models.CharField(max_length=35),
        ),
    ]
