# Generated by Django 3.2.7 on 2022-11-13 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.AlterField(
            model_name='rolgroup',
            name='activo',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
