# Generated by Django 3.2.7 on 2022-09-13 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(blank=True, max_length=150, null=True)),
                ('tabla', models.CharField(blank=True, max_length=2080, null=True)),
                ('data_nueva', models.CharField(blank=True, max_length=2080, null=True)),
                ('data_actual', models.CharField(blank=True, max_length=2080, null=True)),
                ('fecha_creado', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Concursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50, null=True)),
                ('imagen', models.CharField(blank=True, max_length=2080, null=True)),
                ('link', models.CharField(blank=True, max_length=2080, null=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Emisora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frecuencia_dial', models.CharField(blank=True, max_length=30, null=True)),
                ('tipo_frecuencia', models.CharField(blank=True, max_length=30, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('url_streaming', models.CharField(blank=True, max_length=2080, null=True)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('provincia', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=2080, null=True)),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('dia_inicio', models.DateField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('dia_fin', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.CharField(blank=True, max_length=30, null=True)),
                ('ciudad', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=2080, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.CharField(blank=True, max_length=2080, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_emisora', models.ForeignKey(db_column='id_emisora', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.emisora')),
            ],
        ),
        migrations.CreateModel(
            name='Hilochat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(blank=True, max_length=10, null=True)),
                ('id_emisora', models.ForeignKey(db_column='id_emisora', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.emisora')),
            ],
        ),
        migrations.CreateModel(
            name='Locutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.CharField(blank=True, max_length=2080, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, db_column='fecha_Nacimiento', null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField()),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('hora_envio', models.TimeField(blank=True, null=True)),
                ('envio_correo', models.IntegerField()),
                ('tipo_notificacion', models.CharField(max_length=30)),
                ('tipos_usuarios', models.CharField(max_length=30)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PoliticasPriv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=2080, null=True)),
                ('fecha_creado', models.DateField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(null=True, unique=True)),
                ('imagen', models.CharField(blank=True, max_length=2080, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('imagen', models.CharField(blank=True, max_length=2080, null=True)),
                ('logotipo', models.CharField(blank=True, max_length=2080, null=True)),
                ('sitio_web', models.CharField(blank=True, max_length=2080, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RedSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('logo_red_social', models.CharField(blank=True, max_length=2080, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('dias_suscripcion', models.IntegerField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('lugar', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField()),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('url', models.CharField(max_length=300)),
                ('likes', models.IntegerField()),
                ('tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_galeria', models.ForeignKey(db_column='id_galeria', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.galeria')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('encuesta', models.ForeignKey(db_column='encuesta', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.encuesta')),
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioConcursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_concurso', models.ForeignKey(db_column='id_concurso', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.concursos')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('subtitulo', models.CharField(blank=True, max_length=30, null=True)),
                ('url', models.CharField(blank=True, max_length=2080, null=True)),
                ('plataforma', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_emisora', models.ForeignKey(db_column='id_emisora', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.emisora')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonoEmisora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_emisora', models.ForeignKey(db_column='id_emisora', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.emisora')),
            ],
        ),
        migrations.CreateModel(
            name='SugerenciaReclamos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
                ('archivo', models.TextField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('id_radio', models.ForeignKey(blank=True, db_column='id_radio', null=True, on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.radio')),
                ('id_usuario', models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentoEmisora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emisora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.emisora')),
                ('segmento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=30, null=True)),
                ('cliente', models.CharField(blank=True, max_length=30, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=2080, null=True)),
                ('url', models.CharField(blank=True, max_length=2080, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_radio', models.ForeignKey(db_column='id_radio', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.radio')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('id_encuesta', models.ForeignKey(db_column='id_encuesta', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('autores', models.CharField(max_length=30)),
                ('audio', models.CharField(blank=True, max_length=2080, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=2080, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_emisora', models.ForeignKey(db_column='id_emisora', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.emisora')),
            ],
        ),
        migrations.CreateModel(
            name='PartidoTransmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('fecha_evento', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('marcador', models.CharField(blank=True, max_length=20, null=True)),
                ('ptos_equipo_local', models.SmallIntegerField(blank=True, null=True)),
                ('ptos_equipo_visitante', models.SmallIntegerField(blank=True, null=True)),
                ('url_partido', models.CharField(blank=True, max_length=2080, null=True)),
                ('plataforma', models.CharField(blank=True, max_length=30, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_emisora', models.ForeignKey(db_column='id_emisora', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.emisora')),
                ('id_equipo_local', models.ForeignKey(db_column='id_equipo_local', on_delete=django.db.models.deletion.CASCADE, related_name='equipolocal', to='WebAdminRadio.equipo')),
                ('id_equipo_visitante', models.ForeignKey(db_column='id_equipo_visitante', on_delete=django.db.models.deletion.CASCADE, related_name='equipovisitante', to='WebAdminRadio.equipo')),
                ('id_torneo', models.ForeignKey(db_column='id_torneo', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enunciado', models.TextField()),
                ('numero_votos', models.IntegerField(blank=True, null=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.pregunta')),
            ],
        ),
        migrations.CreateModel(
            name='NoticiasTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('fecha_subida', models.DateTimeField(blank=True, null=True)),
                ('imagen', models.CharField(blank=True, max_length=2080, null=True)),
                ('likes', models.IntegerField(blank=True, null=True)),
                ('compartidos', models.IntegerField(blank=True, null=True)),
                ('visualizacion', models.IntegerField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=30, null=True)),
                ('activo', models.IntegerField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_emisora', models.ForeignKey(db_column='id_emisora', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.emisora')),
            ],
        ),
        migrations.CreateModel(
            name='Mensajechat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('fecha_hora_envia', models.DateTimeField()),
                ('id_hilochat', models.ForeignKey(db_column='id_hilochat', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.hilochat')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField(blank=True, null=True)),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_programa', models.ForeignKey(db_column='id_programa', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.programa')),
            ],
        ),
        migrations.CreateModel(
            name='Favorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_segmento', models.ForeignKey(db_column='id_segmento', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.programa')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='encuesta',
            name='id_emisora',
            field=models.ForeignKey(blank=True, db_column='id_emisora', null=True, on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.radio'),
        ),
        migrations.AddField(
            model_name='emisora',
            name='id_radio',
            field=models.ForeignKey(db_column='id_radio', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.radio'),
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_compra', models.FloatField(blank=True, null=True)),
                ('iva', models.FloatField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('id_suscripcion', models.ForeignKey(db_column='id_suscripcion', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.suscripcion')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AnunciosRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('imagen', models.CharField(blank=True, max_length=2080, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('id_radio', models.ForeignKey(db_column='id_radio', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.radio')),
            ],
        ),
        migrations.CreateModel(
            name='UsuariosNotificacion',
            fields=[
                ('id_notificacion', models.OneToOneField(db_column='id_notificacion', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WebAdminRadio.notificacion')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SegmentoLocutor',
            fields=[
                ('id_segmento', models.OneToOneField(db_column='id_segmento', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WebAdminRadio.programa')),
                ('id_locutor', models.ForeignKey(db_column='id_locutor', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.locutor')),
            ],
        ),
        migrations.CreateModel(
            name='RedSocialLocutor',
            fields=[
                ('id_locutor', models.OneToOneField(db_column='id_locutor', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WebAdminRadio.locutor')),
                ('username', models.CharField(blank=True, max_length=150, null=True)),
                ('link', models.CharField(blank=True, max_length=2080, null=True)),
                ('id_red_social', models.ForeignKey(db_column='id_red_social', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.redsocial')),
            ],
        ),
        migrations.CreateModel(
            name='RedSocialEquipo',
            fields=[
                ('id_equipo', models.OneToOneField(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WebAdminRadio.equipo')),
                ('link', models.CharField(blank=True, max_length=2080, null=True)),
                ('estado', models.BooleanField(default=True)),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('id_red_social', models.ForeignKey(db_column='id_red_social', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.redsocial')),
            ],
        ),
        migrations.CreateModel(
            name='RedSocialEmisora',
            fields=[
                ('id_emisora', models.OneToOneField(db_column='id_emisora', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='WebAdminRadio.emisora')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('link', models.CharField(blank=True, max_length=2080, null=True)),
                ('id_red_social', models.ForeignKey(db_column='id_red_social', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.redsocial')),
            ],
        ),
    ]
