# Generated by Django 3.2.7 on 2022-09-21 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0002_alter_emisora_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partidotransmision',
            name='id_emisora',
        ),
        migrations.CreateModel(
            name='PartidoTransmisionEmisora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emisora', models.ForeignKey(db_column='id_emisora', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.emisora')),
                ('id_partido', models.ForeignKey(db_column='id_partido', on_delete=django.db.models.deletion.CASCADE, related_name='partido', to='WebAdminRadio.partidotransmision')),
            ],
        ),
    ]
