# Generated by Django 3.2.7 on 2022-09-21 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0002_alter_emisora_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='redsocialequipo',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redsocialequipo',
            name='id_equipo',
            field=models.OneToOneField(db_column='id_equipo', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.equipo'),
        ),
    ]
