# Generated by Django 3.2.7 on 2022-09-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0004_alter_redsocialequipo_id_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emisora',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
