# Generated by Django 3.2.7 on 2022-09-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0005_alter_emisora_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='dia',
            field=models.CharField(default='Lunes', max_length=9),
            preserve_default=False,
        ),
    ]
