# Generated by Django 3.2.7 on 2022-09-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0003_auto_20220921_1553'),
        ('WebAdminRadio', '0005_alter_emisora_id'),
    ]

    operations = [
    ]
