# Generated by Django 3.2.7 on 2022-09-23 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0006_merge_0003_auto_20220921_1553_0005_alter_emisora_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidotransmision',
            name='imagen',
            field=models.CharField(blank=True, max_length=2080, null=True),
        ),
        migrations.AlterField(
            model_name='partidotransmisionemisora',
            name='id_partido',
            field=models.ForeignKey(db_column='id_partido', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.partidotransmision'),
        ),
    ]
