# Generated by Django 3.2.7 on 2022-09-23 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0006_horario_dia'),
        ('WebAdminRadio', '0008_remove_partidotransmision_imagen'),
    ]

    operations = [
    ]
