# Generated by Django 3.2.7 on 2022-09-26 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0009_merge_20220923_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='redsociallocutor',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='redsociallocutor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='redsociallocutor',
            name='id_locutor',
            field=models.ForeignKey(db_column='id_locutor', on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.locutor'),
        ),
    ]
