# Generated by Django 3.2.7 on 2022-09-27 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0010_auto_20220925_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
