# Generated by Django 3.2.7 on 2022-10-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0011_auto_20220927_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticiastips',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='noticiastips',
            name='compartidos',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='noticiastips',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='noticiastips',
            name='visualizacion',
            field=models.IntegerField(default=0),
        ),
    ]
