# Generated by Django 3.2.7 on 2022-10-05 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0012_auto_20221005_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticiastips',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
