# Generated by Django 3.2.7 on 2022-10-09 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0014_auto_20221006_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='partidotransmision',
            name='estadio',
            field=models.CharField(blank=True, max_length=100, null=True, default=''),
        ),
    ]
