# Generated by Django 3.2.7 on 2022-10-27 23:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0015_partidotransmision_estadio'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicidad',
            name='creada',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
