# Generated by Django 3.2.7 on 2022-12-01 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0017_auto_20221027_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='politicaspriv',
            name='contenido',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='dia_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='dia_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='politicaspriv',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
