# Generated by Django 3.2.7 on 2022-12-09 04:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0018_auto_20221130_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='tipo_pregunta',
            field=models.CharField(choices=[('opcion-multiple', 'OPCION MULTIPLE'), ('opcion-unica', 'OPCION UNICA')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opcionpregunta',
            name='enunciado',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='opcionpregunta',
            name='numero_votos',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='opcionpregunta',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones_set', to='WebAdminRadio.pregunta'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='id_encuesta',
            field=models.ForeignKey(db_column='id_encuesta', on_delete=django.db.models.deletion.CASCADE, related_name='preguntas_set', to='WebAdminRadio.encuesta'),
        ),
    ]
