# Generated by Django 3.2.7 on 2022-12-10 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0019_auto_20221208_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='id_emisora',
            field=models.ForeignKey(blank=True, db_column='id_emisora', null=True, on_delete=django.db.models.deletion.CASCADE, to='WebAdminRadio.emisora'),
        ),
    ]
