# Generated by Django 3.2.7 on 2022-12-14 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebAdminRadio', '0020_alter_encuesta_id_emisora'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='usuarios_encuesta',
            field=models.ManyToManyField(through='WebAdminRadio.UsuarioEncuesta', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='UsuarioDetalleEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_detalle_encuesta_set', to='WebAdminRadio.opcionpregunta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_detalle_encuesta_set', to='WebAdminRadio.pregunta')),
                ('usuario_encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_detalle_encuesta_set', to='WebAdminRadio.usuarioencuesta')),
            ],
        ),
    ]
