# Generated by Django 3.2.7 on 2022-12-25 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebAdminRadio', '0022_auto_20221213_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auditoria',
            old_name='data_actual',
            new_name='imagen',
        ),
        migrations.RenameField(
            model_name='auditoria',
            old_name='data_nueva',
            new_name='link_audio',
        ),
        migrations.RenameField(
            model_name='auditoria',
            old_name='tabla',
            new_name='link_documento',
        ),
        migrations.RemoveField(
            model_name='auditoria',
            name='accion',
        ),
        migrations.AddField(
            model_name='auditoria',
            name='titulo',
            field=models.CharField(blank=True, max_length=2080, null=True),
        ),
        migrations.AlterField(
            model_name='auditoria',
            name='fecha_creado',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuarioencuesta',
            name='fecha',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
